name: Docker CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: electricity-price-prediction:test
        load: true
    
    - name: Run tests in Docker container
      run: |
        docker run --name test-container electricity-price-prediction:test pytest
    
    - name: Copy test results
      run: |
        docker cp test-container:/app/test-results ./test-results
      if: always()
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
      if: always()
    
    - name: Run training script
      run: |
        docker run --name train-container -v ${PWD}/data:/app/data electricity-price-prediction:test python src/train.py
    
    - name: Copy trained model
      run: |
        docker cp train-container:/app/best_model.joblib ./best_model.joblib
    
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: best_model.joblib