name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover tests

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t electricity-price-prediction .
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ lower(github.repository_owner) }}/electricity-price-prediction
        VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
        docker tag electricity-price-prediction $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION