name: Docker CI/CD

on: [push, pull_request]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: electricity-price-prediction:latest
        load: true
    
    - name: Run training script and capture metrics
      run: |
        docker run --name train-container -v ${PWD}/data:/app/data electricity-price-prediction:latest | tee training_output.txt
    
    - name: Extract RMSE metrics
      run: |
        echo "Train RMSE: $(grep 'Train Metrics' training_output.txt | grep -oP 'RMSE: \K[0-9.]+')" >> $GITHUB_STEP_SUMMARY
        echo "Test RMSE: $(grep 'Test Metrics' training_output.txt | grep -oP 'RMSE: \K[0-9.]+')" >> $GITHUB_STEP_SUMMARY
    
    - name: Copy trained model
      run: |
        docker cp train-container:/app/best_model.joblib ./best_model.joblib
    
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: best_model.joblib
    
    - name: Upload training output
      uses: actions/upload-artifact@v2
      with:
        name: training-output
        path: training_output.txt