name: Docker CI/CD

on: [push, pull_request]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: electricity-price-prediction:latest
        load: true
    
    - name: Run training script
      run: |
        docker run --name train-container -v \${PWD}/data:/app/data electricity-price-prediction:latest
    
    - name: Copy trained model
      run: |
        docker cp train-container:/app/electricity_price_model.joblib ./electricity_price_model.joblib
    
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: electricity_price_model.joblib